TengoDotNetCore.Web/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TengoDotNetCore.BLL;

namespace TengoDotNetCore.Controllers {
    public class CartController : BaseController {

        #region Index 我的购物车
        public IActionResult Index() {
            return View();
        }
        #endregion

        #region List 获取购物车列表接口 api/cart/list
        [Route("api/cart/list")]
        public async Task<IActionResult> List([FromServices]CartBLL service) {
            return MyJsonResultSuccess("success", await service.GetUserCartList(1, true));
        }
        #endregion

        #region SetQty 更新覆盖购物车商品数量 幂等! api/cart/setQty
        [Route("api/cart/setQty")]
        public async Task<IActionResult> SetQty([FromServices]CartBLL service, int goodsID, int qty) {
            return MyJsonResult(await service.SetQty(1, goodsID, qty));
        }
        #endregion

        #region RemoveAll 清空购物车 api/cart/removeAll
        [Route("api/cart/removeAll")]
        public async Task RemoveAll([FromServices]CartBLL service) {
            await service.RemoveAll(1);
        }
        #endregion

        #region SetChecked 设置单个商品状态为选中 幂等! api/cart/setChecked
        [Route("api/cart/setChecked")]
        public async Task SetChecked([FromServices]CartBLL service, int goodsID, int selected) {
            await service.SetChecked(1, goodsID, selected);
        }
        #endregion

        #region SetAllChecked 设置所有商品为选中或未选中 幂等! api/cart/setAllChecked
        [Route("api/cart/setAllChecked")]
        public async Task SetAllChecked([FromServices]CartBLL service, int selected) {
            await service.SetAllChecked(1, selected);
        }
        #endregion

        #region BuyAtNow 立即购买 api/cart/buyAtNow
        [Route("api/cart/buyAtNow")]
        public async Task<IActionResult> BuyAtNow([FromServices]CartBLL service, int goodsID, int qty) {
            //将所有的商品设为不选中
            await service.SetAllChecked(1, 0);
            //然后将当前商品的数量设为指定数量并且选中
            return MyJsonResult(await service.SetQty(1, goodsID, qty));
        }
        #endregion
    }
}

TengoDotNetCore.Web/Controllers/GoodsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using TengoDotNetCore.BLL;
using TengoDotNetCore.BLL.Data;
using TengoDotNetCore.Common.BaseModels;

namespace TengoDotNetCore.Controllers {
    public class GoodsController : BaseController {

        #region Index 商品列表
        public async Task<IActionResult> Index([FromServices]GoodsBLL service, [FromServices]TengoDbContext db, PageInfo pageInfo, List<int> categoryID = null, string keyword = null, string sortBy = null) {
            ViewBag.Category = await db.Category.ToListAsync();
            if (pageInfo.PageSize <= 0) {
                pageInfo.PageSize = 60;
            }
            ViewBag.Goods = await service.PageList(pageInfo, categoryID, keyword, sortBy);
            return View();
        }
        #endregion

        #region Detail 商品详情
        public async Task<IActionResult> Detail([FromServices]GoodsBLL service, int id = 0) {
            if (id <= 0) {
                return new NotFoundResult();
            }
            var model = await service.Get(id);
            if (model == null || model.Status != 1) {
                return new NotFoundResult();
            }

            ViewData.Model = model;
            ViewBag.RecGoods = await service.GetRecList(5);
            return View();
        }
        #endregion

        #region RecList 获取推荐商品列表 api/goods/reclist
        [Route("api/goods/reclist")]
        public async Task<IActionResult> RecList([FromServices]GoodsBLL service, int take = 5) {
            return Json(await service.GetRecList(take));
        }
        #endregion
    }
}

TengoDotNetCore.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TengoDotNetCore.BLL;
using TengoDotNetCore.Common;
using TengoDotNetCore.Common.Sessions;
using TengoDotNetCore.Filters;
using TengoDotNetCore.Models;

namespace TengoDotNetCore.Controllers {
    public class UserController : BaseController {

        #region Index 个人中心页面
        [UserFilter]
        public IActionResult Index() {
            return View();
        }
        #endregion

        #region Login 登录页面
        public IActionResult Login() {
            return View();
        }
        #endregion

        #region ApiLogin 登录接口 ----- api/user/login
        [Route("api/user/login")]
        public async Task<IActionResult> ApiLogin([FromServices]UserBLL service, string account, string password) {
            var res = await service.Login(account, password, HttpContext.Connection.RemoteIpAddress.ToString());
            if (res.code == 1000) {//如果登录成功，要设置Session之类的
                HttpContext.Session.Set(Constant.SESSION_USER, res.data);
            }
            return MyJsonResult(res);
        }
        #endregion

        #region Register 注册页面
        public IActionResult Register() {
            return View();
        }
        #endregion

        #region ApiRegister 注册接口 ----- api/user/register
        [Route("api/user/register")]
        public async Task<IActionResult> ApiRegister([FromServices]UserBLL service, User model) {
            if (ModelState.IsValid) {
                model.RegisterIP = HttpContext.Connection.RemoteIpAddress.ToString();
                var res = await service.Insert(model);
                if (res.code == 1000) {//如果注册成功，要设置Session之类的
                    HttpContext.Session.Set(Constant.SESSION_USER, res.data);
                }
                return MyJsonResult(res);
            }
            else {
                return MyJsonResultParamInvalid();
            }
        }
        #endregion
    }
}

TengoDotNetCore.Web/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>@ViewData["Title"] - TengoDotNetCore</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/tengo-dialog/tengo-dialog.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/width.css" rel="stylesheet" />
    <link href="~/css/color.css" rel="stylesheet" />
    <link href="~/lib/tengo-dialog/tengo-dialog.css" rel="stylesheet" />
    @RenderSection("Header", required: false)
</head>
<body>
    @*新的写法，而不是以前的 Html.Partial*@
    <partial name="_LayoutHeader" />

    @RenderBody()

    <partial name="_LayoutFooter" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/utils.js"></script>
    <script src="~/lib/tengo-dialog/tengo-dialog.js"></script>
    @RenderSection("Footer", required: false)
</body>
</html>

TengoDotNetCore.Web/Views/Shared/_LayoutFooter.cshtml
@{
    Layout = null;
}
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2018 - TengoDotNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

TengoDotNetCore.Web/Views/Shared/_LayoutHeader.cshtml
@{
    Layout = null;
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tengo电商</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">首页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Goods" asp-action="Index">商品列表</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">我的购物车</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">个人中心</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index" target="_blank">后台管理</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container body-content">
    <partial name="_CookieConsentPartial" />
</div>

TengoDotNetCore.Web/Views/Shared/_LayoutVue.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>@ViewData["Title"] - TengoDotNetCore</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/tengo-dialog/tengo-dialog.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/width.css" rel="stylesheet" />
    <link href="~/css/color.css" rel="stylesheet" />
    <link href="~/lib/tengo-dialog/tengo-dialog.css" rel="stylesheet" />
    @RenderSection("Header", required: false)
</head>
<body>
    <partial name="_LayoutHeader" />
    <div class="container body-content">
        <partial name="_CookieConsentPartial" />
    </div>
    <div id="app">
        @RenderBody()
    </div>
    <partial name="_LayoutFooter" />
    <environment include="Development">
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    </environment>
    <script src="https://cdn.staticfile.org/vue-resource/1.5.1/vue-resource.min.js"></script>
    <script src="~/lib/tengo-dialog/tengo-dialog.js"></script>
    <script src="~/js/utils.js"></script>
    @RenderSection("Footer", required: false)
</body>
</html>